spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/antiplagiarism
    username: postgres
    password: temp_Orange100
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 30MB
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
